// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package main

import "encoding/json"
import "fmt"
import "time"

// The payload edgar-fetcher POSTs to edgar-parser. Intentionally both the current
// wire format and the future queue-message format.
type FilingEnvelope struct {
	// EDGAR's unique ID for the submission, e.g. "0001234567-26-000123".
	AccessionNumber string `json:"accession_number" yaml:"accession_number" mapstructure:"accession_number"`

	// As printed in EDGAR's daily index — may or may not be zero-padded to 10 digits.
	CIK string `json:"cik" yaml:"cik" mapstructure:"cik"`

	// RFC 3339 timestamp of when edgar-fetcher retrieved the filing.
	FetchedAt time.Time `json:"fetched_at" yaml:"fetched_at" mapstructure:"fetched_at"`

	// YYYY-MM-DD, as printed in EDGAR's daily index.
	FiledAt string `json:"filed_at" yaml:"filed_at" mapstructure:"filed_at"`

	// e.g. "4" for a Form 4 insider transaction filing.
	FormType string `json:"form_type" yaml:"form_type" mapstructure:"form_type"`

	// The unparsed filing content.
	RawXML string `json:"raw_xml" yaml:"raw_xml" mapstructure:"raw_xml"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FilingEnvelope) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["accession_number"]; raw != nil && !ok {
		return fmt.Errorf("field accession_number in FilingEnvelope: required")
	}
	if _, ok := raw["cik"]; raw != nil && !ok {
		return fmt.Errorf("field cik in FilingEnvelope: required")
	}
	if _, ok := raw["fetched_at"]; raw != nil && !ok {
		return fmt.Errorf("field fetched_at in FilingEnvelope: required")
	}
	if _, ok := raw["filed_at"]; raw != nil && !ok {
		return fmt.Errorf("field filed_at in FilingEnvelope: required")
	}
	if _, ok := raw["form_type"]; raw != nil && !ok {
		return fmt.Errorf("field form_type in FilingEnvelope: required")
	}
	if _, ok := raw["raw_xml"]; raw != nil && !ok {
		return fmt.Errorf("field raw_xml in FilingEnvelope: required")
	}
	type Plain FilingEnvelope
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = FilingEnvelope(plain)
	return nil
}
